#FROM centos:centos6
# 
#RUN yum -y update
#RUN yum -y install gcc git tar openssl openssl-devel
# 
# rbenvのインストール
#RUN git clone https://github.com/sstephenson/rbenv.git /root/.rbenv
#RUN git clone https://github.com/sstephenson/ruby-build.git /root/.rbenv/plugins/ruby-build
#RUN ./root/.rbenv/plugins/ruby-build/install.sh
#ENV PATH /root/.rbenv/bin:$PATH
#RUN echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
#RUN echo 'eval "$(rbenv init -)"' >> .bashrc
# 
## rubyのインストール
#ENV CONFIGURE_OPTS --disable-install-doc
#RUN rbenv install 2.1.1
#RUN rbenv global 2.1.1

FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
#RUN mkdir /myapp
#WORKDIR /myapp
#COPY Gemfile /myapp/Gemfile
#COPY Gemfile.lock /myapp/Gemfile.lock
#RUN bundle install
#COPY . /myapp
